info:
    name: @project.name@
    team: proj
    version: @project.version@
    servicename: url-shortener-service

server:
    port: 8080

management:
    server:
        port: 8082
    endpoints:
        web:
            exposure:
                include: health,prometheus
            base-path: /system
            path-mapping:
                health: health
    endpoint:
        health:
            probes:
                enabled: true
